
serviceAccount: 'projects/$PROJECT_ID/serviceAccounts/cicd-test1-492416-gcb@cicd-test1-492416.iam.gserviceaccount.com'
steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '$LOCATION-docker.pkg.dev/$PROJECT_ID/cicd-demo/spring-petclinic:$COMMIT_SHA', '.']

  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '$LOCATION-docker.pkg.dev/$PROJECT_ID/cicd-demo/spring-petclinic:$COMMIT_SHA']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'spring-petclinic'
      - '--image'
      - '$LOCATION-docker.pkg.dev/$PROJECT_ID/cicd-demo/spring-petclinic:$COMMIT_SHA'
      - '--region'
      - '$_REGION'
      - '--allow-unauthenticated'

images:
  - '$LOCATION-docker.pkg.dev/$PROJECT_ID/cicd-demo/spring-petclinic:$COMMIT_SHA'

options:
  requestedVerifyOption: VERIFIED
  logging: CLOUD_LOGGING_ONLY
